---
title: "R Notebook"
output: html_notebook
---

Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.
```{r}
print("Hello Notebook")
```
```{r}
y = c(3,4,5)
A = cbind(rep(2,length(y)),y)
A
```
```{r}
A[1]
A[1,2]
A[1,]
A[2,]
```

```{r}
#Subscripting: positive and negative
B = rbind(rep(2,length(y)),y)
B
t(A) == B
sum(t(A) == B)

```
```{r}
#Ranges and looping:
n <- 12
z <- 1:n
z
z2= z <- c(1:n)
z2

z3 <- vector(length=n)
z3

for(i in 1:n) {z3[i] <- i}
z3

```
```{r}
#Matrices and arrays:
mat2by4 <- matrix(1:8, nrow=2, ncol=4)
mat2by4

arr3by4by2 <- array(1:24, dim=c(2,4,3))
arr3by4by2

arr2by4by3 <- array(1:24, dim=c(3,4,2))
```

```{r}
length(c(-3,-4))

dim(arr2by4by3[1,c(-3,-4),])

A <- arr2by4by3[1,c(-3,-4),]
t(A)

```

```{r}
#Numeric, Statistical, and Character Functions
options(digits=10)
pi = 3.1415926535897932384626
pi

```
```{r}
#Random sampling:
plot(density(rbinom(50,50,1/2)))

```
```{r}
options(digits=6)
set.seed(49)
sample(10, replace = TRUE)
```

```{r}
#String concatenation:
print(paste("PCLN","UNP","IBM","MCD","PFE",sep=","))

```

```{r}
#Date and string functions:
date <- as.Date("2014-02-01")
substr(date,9,11)

```

```{r}
#String array:
tickers <- c("PCLN","UNP","IBM","MCD","PFE")
match('MCD',tickers)
```

```{r}
#Data Frames and Input–Output
L3 <- LETTERS[1:3]
fac <- sample(L3, 10, replace = TRUE)
d <- data.frame(x = 1, y = 1:10, fac = fac)
d[1:10,]

d$fac
```

```{r}
#Input-ouput:
write.csv(d,file="d.txt",row.names=FALSE)
e <- read.csv("d.txt",header=TRUE)
e[1:4,]
```

